from unittest.case import _BaseTestCaseContext


TICK=10
CYCLE=20
LIMIT=300
COIN='BTC'
SYMBOL='BTCUSD'
PRICE_COL='Close'
TIMEFRAME=1 #In minutes
DATA_DIR='data'
TAKE_PROFIT=1.10
STOP_LOSS=0.90
START_CAPITAL=100000